create table AUTH_USER
(
    ID                      CHARACTER VARYING,
    CREATE_DATE             TIMESTAMP WITH TIME ZONE,
    UPDATE_DATE             TIMESTAMP WITH TIME ZONE,
    USERNAME                CHARACTER VARYING,
    PASSWORD                CHARACTER VARYING,
    ENABLED                 BOOLEAN NOT NULL,
    ACCOUNT_NON_EXPIRED     BOOLEAN NOT NULL,
    CREDENTIALS_NON_EXPIRED BOOLEAN NOT NULL,
    ACCOUNT_NON_LOCKED      BOOLEAN NOT NULL
);
ALTER TABLE AUTH_USER
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (ID);

create table ROLE
(
    ID          CHARACTER VARYING,
    CREATE_DATE TIMESTAMP WITH TIME ZONE,
    UPDATE_DATE TIMESTAMP WITH TIME ZONE,
    NAME        CHARACTER VARYING NOT NULL,
    CODE        CHARACTER VARYING NOT NULL
);
ALTER TABLE role
    ADD CONSTRAINT role_pkey PRIMARY KEY (ID);

create table PERMISSION
(
    ID          CHARACTER VARYING NOT NULL,
    CREATE_DATE TIMESTAMP WITH TIME ZONE,
    UPDATE_DATE TIMESTAMP WITH TIME ZONE,
    NAME        CHARACTER VARYING NOT NULL,
    CODE        CHARACTER VARYING NOT NULL
);
ALTER TABLE permission
    ADD CONSTRAINT permission_pkey PRIMARY KEY (id);

create table ROLE_AUTH_USER
(
    USER_ID CHARACTER VARYING NOT NULL REFERENCES AUTH_USER (ID) ON UPDATE CASCADE ON DELETE CASCADE,
    ROLE_ID CHARACTER VARYING NOT NULL REFERENCES ROLE (ID) ON UPDATE CASCADE,
    CONSTRAINT role_auth_user_pkey PRIMARY KEY (USER_ID, ROLE_ID)
);

CREATE TABLE PERMISSION_ROLE
(
    ROLE_ID       CHARACTER VARYING NOT NULL REFERENCES ROLE (ID) ON UPDATE CASCADE ON DELETE CASCADE,
    PERMISSION_ID CHARACTER VARYING NOT NULL REFERENCES PERMISSION (ID) ON UPDATE CASCADE,
    CONSTRAINT permission_role_pkey PRIMARY KEY (ROLE_ID, PERMISSION_ID)
);

INSERT INTO PERMISSION(ID, CREATE_DATE, UPDATE_DATE, NAME, CODE)
VALUES ('e6336fe0-2642-47b2-887a-7fa26263f60d', NOW(), NULL, 'Create Product', 'create_product');

INSERT INTO ROLE(ID, CREATE_DATE, UPDATE_DATE, NAME, CODE)
VALUES ('9922b2de-5991-4a2f-9ff3-4c9cb7db3f3e', NOW(), NULL, 'Seller', 'seller');

INSERT INTO AUTH_USER(ID, CREATE_DATE, UPDATE_DATE, USERNAME, PASSWORD, ENABLED, ACCOUNT_NON_EXPIRED,
                      CREDENTIALS_NON_EXPIRED, ACCOUNT_NON_LOCKED)
VALUES ('6beb3d3c-9da2-4863-a627-2fb540c1d324', NOW(), NULL, 'caner.kaya',
        '$2a$10$mJOP1KyxMYAySEEAdyoNdebDSKf11kvQABOi1442EZENqDWw8Vtti', true, true, true, true);

INSERT INTO PERMISSION_ROLE (ROLE_ID, PERMISSION_ID)
VALUES ('9922b2de-5991-4a2f-9ff3-4c9cb7db3f3e', 'e6336fe0-2642-47b2-887a-7fa26263f60d');

INSERT INTO ROLE_AUTH_USER(USER_ID, ROLE_ID)
VALUES ('6beb3d3c-9da2-4863-a627-2fb540c1d324', '9922b2de-5991-4a2f-9ff3-4c9cb7db3f3e');
